### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by AstroJacobLi** [AstroJacobLi/slug#1]
- [x] Plot intermediate-z sample main figure ASAP!
- [ ] How to do with the ellipse error when doing the main figure?
- [x] update sample distribution histogram using FDFC new (and also final) sample
- [ ] Modify `display` functions!

**Comment by AstroJacobLi** [comment]
- [ ] Low-z: make upper-limit figure, estimate bkg error for each image. Run `tractor` on low-z galaxies or do `tractor` mock tests on low-z galaxies?
- [ ] Intermediate-z: how to interpret the result? How to make interpolation?
- [ ] Small scatter of median profile: how to calculate error? on which level?

**Comment by AstroJacobLi** [comment]
Interpolation of profile: over-sampling?
